//
//  PoseDataStore.swift
//  PoseFinder
//
//  Created by iOS Dev on 01/12/25.
//  Copyright © 2025 Apple. All rights reserved.
//

import Foundation

struct PoseDataStore {
    
    private static let fileName = "urdf_joint_log.json"
    
    /**
     The file URL pointing to the persistent storage location in the Documents directory.
     */
    private static var fileURL: URL {
        guard let documentsDirectory = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            fatalError("Could not access Documents directory.")
        }
        return documentsDirectory.appendingPathComponent(fileName)
    }
    
    /**
     Retrieves all stored URDF joint XML strings. If the file is not found, it provides mock data
     to ensure the simulation can run immediately.
     */
    static func getAllData() -> [String] {
        guard let data = try? Data(contentsOf: fileURL),
              let stringArray = try? JSONSerialization.jsonObject(with: data, options: []) as? [String] else {
            return mockInitialData()
        }
        return stringArray
    }
    
    /**
     Generates a small set of mock pose data (XML strings) for demonstration
     when no real data file exists.
     */
    static func mockInitialData() -> [String] {
        // Sample angles for demonstration
        let leftShoulderRad: Float = 30 * .pi / 180 // 30 degrees forward
        let rightShoulderRad: Float = -30 * .pi / 180 // 30 degrees backward
        let leftKneeRad: Float = 45 * .pi / 180 // 45 degrees bend
        let zeroRad: Float = 0
        
        let xmlTemplate = """
        <joint name="%@" type="revolute">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <axis xyz="1 0 0"/>
            <limit lower="-3.14159" upper="3.14159" effort="50" velocity="2"/>
            <state position="%f"/>
        </joint>
        """
        
        let joints = [
            "leftshoulder_joint", "leftelbow_joint", "rightshoulder_joint", "rightelbow_joint",
            "lefthip_joint", "leftknee_joint", "righthip_joint", "rightknee_joint"
        ]
        
        var mockData: [String] = []
        
        // Pose 1: Left arm up, Right arm straight
        for joint in joints {
            let angle: Float
            switch joint {
            case "leftshoulder_joint": angle = leftShoulderRad
            case "leftknee_joint": angle = leftKneeRad
            default: angle = zeroRad
            }
            mockData.append(String(format: xmlTemplate, joint, angle))
        }
        
        // Pose 2: All straight (zero position)
        for joint in joints {
            mockData.append(String(format: xmlTemplate, joint, zeroRad))
        }
        
        // Pose 3: Right arm up, Left arm straight
        for joint in joints {
            let angle: Float
            switch joint {
            case "rightshoulder_joint": angle = rightShoulderRad
            case "rightknee_joint": angle = leftKneeRad
            default: angle = zeroRad
            }
            mockData.append(String(format: xmlTemplate, joint, angle))
        }
        
        print("PoseDataStore: Using mock data for simulation.")
        return mockData
    }
    
    /**
     Appends a new URDF joint XML string to the storage file.
     */
    static func appendData(xmlString: String) {
        
        var existingData = getAllData()
        
        // Remove mock data if present before appending real data
        if existingData.count > 0 && existingData.first!.contains("1 0 0") {
            // Simple check to see if it's mock data generated by the function above
            existingData = []
        }
        
        existingData.append(xmlString)
        
        do {
            let combinedData = try JSONSerialization.data(withJSONObject: existingData, options: .prettyPrinted)
            try combinedData.write(to: fileURL)
            print("PoseDataStore: Successfully appended new URDF entry. Total entries: \(existingData.count)")
        } catch {
            print("PoseDataStore: Failed to append data: \(error.localizedDescription)")
        }
    }
    
    /**
     Deletes the stored URDF data file.
     */
    static func clearAllData() {
        let fileManager = FileManager.default
        if fileManager.fileExists(atPath: fileURL.path) {
            do {
                try fileManager.removeItem(at: fileURL)
                print("PoseDataStore: Successfully cleared all stored URDF data.")
            } catch {
                print("PoseDataStore: Failed to clear data: \(error.localizedDescription)")
            }
        } else {
            print("PoseDataStore: Log file does not exist, nothing to clear.")
        }
    }
}
